### ISSUE TITLE
I think it does not work with Web API v2.

### ISSUE THREAD

**Issue by narmontas** [Sebazzz/SDammann.WebApi.Versioning#25]

**Comment by sashulyak** [comment]
Hi all!

Still have problems with attribute routing Web API 2.

In this commit @diegohb added attribute routing to only Version1.HelloController.
https://github.com/diegohb/SDammann.WebApi.Versioning/commit/d0ee1697d6236c0c0383637ee55c4072d9109c11

But when I add the same controller int Version2.HelloController (completely identical) I got System.Collections.Generic.KeyNotFoundException.

Stack Trace:

System.Collections.Generic.Dictionary`2.get_Item(TKey key) in System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.FindActionMatchRequiredRouteAndQueryParameters(IEnumerable`1 candidatesFound) in System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.FindMatchingActions(HttpControllerContext controllerContext, Boolean ignoreVerbs) in System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext) in System.Web.Http.Controllers.ApiControllerActionSelector.SelectAction(HttpControllerContext controllerContext) in System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken) in System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()

**Comment by dernippel** [comment]
Hi,

I have the same error like @sashulyak. Does anyone have a solution for this?

**Comment by forsytbe** [comment]
@Sebazzz Hey, I'm trying to get this library working and I'm having the same issue that @sashulyak and @drzsandiego are having.

I only see this happen when I attempt to hit the V1 instance of my endpoint (v2 works fine).

Another thing worth pointing out:  
  Only the routes on my Version2.Controller end up in the RouteTable--  That is, an endpoint on my Version1.Controller does not exist in Version2.Controller, and attempting to hit that endpoint results in 404 because it never made it into the RouteTable.  How this is happening makes total sense: VersionedApiControllerSelector.GetControllerMappings is returning a dictionary<string, MultiVersionHttpControllerDescriptor>, which is then iterated over

`//ApiControllerActionSelector.ActionSelectorCacheItem.ctor`
`
...  
 MethodInfo[] allMethods = _controllerDescriptor.ControllerType.GetMethods(BindingFlags.Instance | BindingFlags.Public);
....
`
to produce a _combinedActionNameMapping for each ControllerDescriptor.  MultiVersionHttpControllerDescriptor.ControllerType is going to be the 'originalDescriptor.ControllerType', so it makes sense that this doesn't work.  I don't know of an easy way to remedy this :(

Please let me know if this is/will be resolved, this seems like a nice lightweight library for versioning.  After about 12 hours of trying to get this working, I have to move on, I can't use it without support for attribute routing :(
